# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.1

jobs:
  test:
    docker:
      - image: cimg/node:12.15.0-browsers
        auth:
          username: leereichardt # can specify string literal values
          password: $DOCKERHUB_PASSWORD # or project environment variable reference
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - install
      - run:
          name: Run Stencil Tests
          command: npm run test

commands:
  install:
    steps:
      - checkout
      - run: npm ci


workflows:
  Test and Deploy:
    jobs:
      - test:
          context:
            - docker-hub-creds
