# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.1

jobs:
  testing:
    docker:
      - image: circleci/node:latest-browsers
#    executor: my-executor
    steps:
      - run: 'npm run test'

workflows:
  Test and Deploy Workflow:
    jobs:
      - testing