# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  puppeteer: threetreeslight/puppeteer@0.1.2
  node: circleci/node@4.1

jobs:
  test:
    docker:
      - image: cimg/node:latest
    steps:
      - puppeteer/install

workflows:
  Test and Deploy Workflow:
    jobs:
      - node/test
#workflows:
#  Testing:
#    jobs:
#      - node/test:
#          version: '15.1'
          # This is the node version to use for the `cimg/node` tag
          # Relevant tags can be found on the CircleCI Developer Hub
          # https://circleci.com/developer/images/image/cimg/node
